name: qia_app
description: QIA Assistant
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  web_socket_channel: ^2.4.0
  path_provider: ^2.1.1
  http: ^1.1.0
  json_annotation: ^4.8.1
  flutter_secure_storage: ^8.0.0
  permission_handler: ^10.2.0
  workmanager: ^0.5.1
  battery_plus: ^4.0.0
  jwt_decoder: ^2.0.1
  local_auth: ^2.1.6
  crypto: ^3.0.3
  encrypt: ^5.0.3
  timeago: ^3.5.0
  speech_to_text: ^6.3.0
  avatar_glow: ^2.0.2
  flutter_animate: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 